name: PR Checks

on:
    pull_request:

jobs:
    run-doc-examples:
        name: Execute examples
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version-file: .nvmrc
            - name: Build SDK
              run:  |
                yarn install
                yarn build
                cd docs
                yarn install
            - name: Run examples
              run: |
                cd docs
                yarn test:examples
    